course/urls.py
from django.urls import path
from course import views

app_name = 'course'

urlpatterns = [
    path('student/<int:student_id>/', views.student_information, name='see_student'),
    path('student/<int:student_id>/edit', views.create_student, name='edit_student'),
    path('student/<int:student_id>/delete', views.confirm_deletion_student, name='confirm_deletion_student'),
    path('student/<int:student_id>/accepted_delete/', views.delete_student, name='delete_student'),
    path('course/<int:class_id>', views.main_data, name='main_data'),
    path('course/student/', views.create_student, name='new_student'),
    path('student/list/', views.list_of_students, name='students_list'),
    path('course/training-unit', views.create_unit, name='new_unit'),
    path('training-unit/list/', views.list_of_training_units, name='units_list'),
    path('training-unit/<int:unit_code>', views.unit_information, name='see_unit'),
    path('', views.index, name='class_index')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings # Forma de importar variáveis existentes dentro do settings.py

		
urlpatterns = [
    path('', include('course.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

course/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class TrainingUnit(models.Model):
    code = models.CharField(max_length=5, primary_key=True)
    subject = models.CharField(max_length=50)
    hours = models.SmallIntegerField(choices=[(25,"25 hours"),(30,"30 hours"),(50,"50 hours"),(75,"75 hours")])
    period = models.SmallIntegerField(choices=[(1,"First period"),(2,"Second period"),(3,"Third period")])
    all_classes = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.code}- { self.subject}'

class Class(models.Model):
    class Meta:
        verbose_name = 'Class'
        verbose_name_plural = 'Classes'
    
    acronym = models.CharField(max_length=2)
    name = models.CharField(max_length=75, blank=True)
    picture = models.ImageField(blank=True,upload_to='pictures/%Y/%m/')
    closed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.acronym}'

class ClassesUnit(models.Model):
    unit = models.ForeignKey(TrainingUnit, on_delete=models.CASCADE)
    unit_class = models.ForeignKey(Class, on_delete=models.CASCADE)
    
    class Meta: 
        verbose_name = 'Classes Unit'
        verbose_name_plural = 'Classes Units'
        constraints = [
            models.UniqueConstraint(
                fields=['unit', 'unit_class'], name='unique_unit_class_combination'
            )
        ]
    
    def __str__(self):
        return f'{self.unit_class}- {self.unit}'

class Student(models.Model):    
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    sex = models.CharField(
                    max_length=6, 
                    choices=[
                                ('F','Female'),
                                ('M','Male')
                            ]
                    )
    city = models.CharField(
                    max_length=20, 
                    blank=True,
                    choices=[
                                ('FML','Famalicão'),
                                ('FRM','Freamunde'),
                                ('PFR','Paços de Ferreira'),
                                ('STR','Santo Tirso')
                            ]
                    )
    dropout = models.BooleanField(default=False)
    my_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return f'{self.name}'
    
class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.DO_NOTHING)
    training_unit = models.ForeignKey(TrainingUnit, on_delete=models.SET_NULL, null=True)
    grade = models.FloatField()
    released_date = models.DateTimeField(default=timezone.now)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['student', 'training_unit'], name='unique_student_unit_combination'
            )
        ]
    
    def __str__(self):
        return f'{self.student} - {self.training_unit} ({self.grade})'

course/views/class_views.py
from django.shortcuts import render
from course.models import Class, TrainingUnit, Student, ClassesUnit

# Create your views here.
def index(request):
    classes = Class.objects.all().filter(closed=False)
    context = {
        'page_title': 'Office Course',
        'classes': classes,
        'header': False
    }
    return render(
        request,
        'course/index.html',
        context
    )

def main_data(request,class_id):
    my_class = Class.objects.get(pk=class_id)
    students = Student.objects.filter(my_class=class_id)
    training_units = ClassesUnit.objects.filter(unit_class=class_id)
    print(training_units)
    context = {
        'page_title': 'Class Students and Training Units',
        'myclass': my_class,
        'students': students,
        'units': training_units,
        'header': True
    }
    return render(
        request,
        'course/main_data.html',
        context
    )

course/views/student_views.py
from django.shortcuts import render, get_object_or_404, redirect
from course.models import Student, Grade
from forms import StudentForm
from django.core.paginator import Paginator

# Create your views here.
def list_of_students(request):
    students = Student.objects.all()
    paginator = Paginator(students, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_title': 'List of students',
        'page_obj': page_obj,
        'header': True
    }
    return render(
        request,
        'course/student/list.html',
        context
    )

def student_information(request, student_id):
    student = Student.objects.get(pk=student_id)
    grades = Grade.objects.filter(student=student_id).order_by('grade')
    context = {
        'page_title': 'List of students',
        'student': student,
        'grades': grades,
        'header': True
    }
    return render(
        request,
        'course/student/student.html',
        context
    )

def create_student(request, student_id = None):
    if student_id:
        student = get_object_or_404(Student, pk=student_id)
        title = "Edit Student"
        if request.method == 'POST':
            form = StudentForm(data = request.POST, instance=student)
            context = { 
                'page_title': 'Edit student',
                'form': form,
                'header': True,
                'student': student,
                'title': title,
                'button': 'Update student data'
            }
            
            if form.is_valid():
                form.save()
                return redirect('course:students_list')

            return render(
                request,
                'course/student/create.html',
                context
            )
        
        # If method s GET ...
        context = {
            'page_title': 'Add new student',
            'form': StudentForm(instance=student),
            'header': True,
            'student': student,
            'title': title,
            'button': 'Update student data'
        }
        return render(
            request,
            'course/student/create.html',
            context
        )
    else:
        title = "Add new student"
        if request.method == 'POST':
            form = StudentForm(data=request.POST)
            context = {
                'page_title': 'Add new student',
                'form': form,
                'header': True,
                'title': title,
                'button': 'Add student'
            }
            
            if form.is_valid():
                form.save()
                return redirect('course:students_list')

            return render(
                request,
                'course/student/create.html',
                context
            )
        
        context = {
            'page_title': 'Add new student',
            'form': StudentForm(),
            'header': True,
            'title': title,
            'button': 'Add student'
        }
        return render(
            request,
            'course/student/create.html',
            context
        )

def confirm_deletion_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    title = 'Deletion of student'
    
    context = {
                'page_title': 'Confirm deletion of student',
                'header': True,
                'title': title,
                'student': student
            }
    
    return render(
        request,
        'course/student/confirm_deletion.html',
        context
    )

def delete_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    print(student)
    
    if student is not None:
        student.delete()
        return redirect('course:students_list')
    
    return render(
                request,
                'course/student/confirm_deletion.html',
            )

course/views/training_unit_views.py
from django.shortcuts import render, redirect
from course.models import TrainingUnit
from django import forms
from django.core.paginator import Paginator
from forms import TrainingUnitForm

def list_of_training_units(request):
    units = TrainingUnit.objects.all()
    paginator = Paginator(units, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_title': 'List of training units',
        'page_obj': page_obj,
        'header': True
    }
    return render(
        request,
        'course/training_unit/list.html',
        context
    )

def unit_information(request, unit_code):
    unit = TrainingUnit.objects.get(pk=unit_code)
    context = {
        'page_title': 'Training unit information',
        'unit': unit,
        'header': True
    }
    return render(
        request,
        'course/training_unit/unit.html',
        context
    )

def create_unit(request):
    title = "Add new training unit"
    if request.method == 'POST':
        form = TrainingUnitForm(data=request.POST)
        context = {
            'page_title': 'Add new unit',
            'form': form,
            'header': True,
            'title': title,
        }
        
        if form.is_valid():
            form.save()
            return redirect('course:units_list')

        return render(
            request,
            'course/training_unit/create.html',
            context
        )
    
    context = {
        'page_title': 'Add new unit',
        'form': TrainingUnitForm(),
        'header': True,
        'title': title,
    }
    return render(
        request,
        'course/training_unit/create.html',
        context
    )

course/templates/course/training_unit/create.html
{% extends "global/base.html" %}

{% block content %}
    <main class="data">
        <span class="title">{{ title }}</span>
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                {% if field.label == 'Subject' %}
                    <div class="col-4">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% else %}
                    <div class="col-5 caption">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <input type="submit" value="Save unit">
        </form>
    </main>
{% endblock content %}

course/templates/course/training_unit/list.html
{% extends "global/base.html" %}

{% block content %}
    <section class="content-student">
        <table class="students-table">
            <caption class="caption-table">List of Training Units</caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Code</th>
                    <th class="table-header major">Subject</th>
                    <th class="table-header">Hours</th>
                    <th class="table-header">Period</th>
                    <th class="table-header">Active?</th>
                    <th class="table-header">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for unit in page_obj %}
                <tr class="table-row">
                    <td class="table-cel center">{{ unit.code }}</td>
                    <td class="table-cel major">{{ unit.subject }}</td>
                    <td class="table-cel center">{{ unit.hours }} hours</td>
                    <td class="table-cel center">{{ unit.period }}</td>
                    <td class="table-cel center">
                        {% if unit.active %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </td>
                    <td class="table-cel center">
                        <a href="{% url "course:see_unit" unit.code %}">Edit</a>
                        <a href="#">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                <tr class="table-row">
                    <th class="table-header page-bar" colspan="7">
                        {% include "global/partials/pagination.html" %}
                    </th>
                </tr>
                <tr class="table-row last">
                    <td colspan="7" class="right">
                        <a href="{% url 'course:new_unit' %}" class="insert">Add new training unit</a>
                    </td>
                </tr>
            </tbody>
        </table>
        
    </section>
{% endblock content %}

course/templates/course/training_unit/unit.html
{% extends "global/base.html" %}

{% block content %}
    <main class="data">
        <span class="title">TRAINING UNIT INFORMATION</span>
        <div class="student-information">
            <p><b>Code:</b> {{ unit.code }}</p>
            <p><b>Unit:</b> {{ unit.subject }}</p>
            <p><b>Hours:</b> {{ unit.hours }} hours</p>
            <p><b>Period:</b> {{ unit.period }}</p>
            <p>
                <b>All Classes?</b> 
                {% if unit.all_classes %}
                    Yes
                {% else %}
                    No
                {% endif %}
            </p>
        </div>
    </main>
    <div class="buttons">
        <a href="#">Edit unit</a>
        <a href="#">
            Delete unit
        </a>
    </div>
{% endblock content %}